### ISSUE TITLE
MoneyForKill PlugIn nicht auf GitHub

### ISSUE THREAD

**Issue by HimbeersaftLP** [SurvivalHive/Minecraft-Pocket-Edition#4]
Wieso?

**Comment by StephanToGo** [comment]
musste mal aufraeumen kanns aber wieder online stellen

**Comment by inxomnyaa** [comment]
Es gibt ja KillMoney, dies hier scheint aber cooler gewesen zu sein

**Comment by StephanToGo** [comment]
weis nicht... war sehr simpel gestrickt

**Comment by StephanToGo** [comment]
achja warum pinkeln die sich so an weiste das?

[LINK](https://github.com/ImagicalMine/ImagicalMine/issues/231416#issuecomment-209358891)

**Comment by HimbeersaftLP** [comment]
Ja, manche auf dem GitHub von IM sind manchmal n' bisschen unhöflich. Aber ich hab das gleiche Problem, ist aber nicht schlimm, wenn eh alles geht ;)

**Comment by StephanToGo** [comment]
is ja auch nur ein programmier fehler... wollte sie lediglich auf den "müll" hinweisen...
aber wenn man so behindert antwortet "lern php" krieg ich zuviel xD

**Comment by HimbeersaftLP** [comment]
Zu mir hat das noch nie wer gesagt, und ich kann nicht mal so gut php wie du. xD

**Comment by StephanToGo** [comment]
Money4Kill ist wieder Online...

**Comment by inxomnyaa** [comment]
die haben echt komplexe, deshalb hatten wir es verlassen..

ClearSky ist nicht so bekannt aber performanter in php5

Hast morgen zeit für ts?

**Comment by StephanToGo** [comment]
sollte passen gegen 20:30 sofern es nicht regnet dann bin ich früher da xD will noch was motorrad fahren

**Comment by inxomnyaa** [comment]
auf deinem?

**Comment by StephanToGo** [comment]
mir egal sonst sag einen dann komm ich dahin

**Comment by HimbeersaftLP** [comment]
Aber hat ClearSky auch ein Forum? xD

**Comment by inxomnyaa** [comment]
Nein, warum auch, wir haben einen Chat :P telegram

**Comment by HimbeersaftLP** [comment]
:O

**Comment by StephanToGo** [comment]
mal ne frage bei meinen Motd Editor... weis jmd warum 
der Server zwar läuft aber sich aufhängt sodass niemand mehr joinen kann?
er wird nach 10sek alls offline deklariert läuft aber weiter.
und dann nut wenn ich $this->getServer()->getNetwork()->setName mache... weis leider keinen rat grade...
