### ISSUE TITLE
Don't working!

### ISSUE THREAD

**Issue by tamaskis99** [SurvivalHive/Minecraft-Pocket-Edition#8]
This plugin doesn't working :/ Can't be loading the server file. Multicraft server manager on VPS my thing. Please help me any knowledge, or fix the problem.

**Comment by StephanToGo** [comment]
which plugin u meen exatcly from all in this package?

**Comment by tamaskis99** [comment]
Ops, sorry... Is that the SurvivalHiveHungerGames plugin.

**Comment by StephanToGo** [comment]
not only... in this package are all of my plugins... so if u want to use hungergames u only need the survivalhivehungergames folder

**Comment by tamaskis99** [comment]
Yes, i maked Hungergames plugin with Eclipse  only hungergames folder source... But, plugin don't starting, no crashing, not do anything...

**Comment by StephanToGo** [comment]
then u do something wrong... zip plugin.yml and src folder and go on http://pmt.mcpe.me/pocketmine.php
